version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: demopod
      POSTGRES_PASSWORD: "17uVquHCyGI5vxhjaPLPXuZBB-C5p2h8"
    volumes:
      - demopod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "n2pZCGRjGjqGdrK8nwYs3C55iQVPnkSc"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  demopod_data:
